const hashtags = [
    'CallOfDutyModernWarfare',
    'callofduty',
    'codtopplays',
    'codclips',
    // 'gaming',
    // 'ps5',
    // 'xbox',
    // 'pc',
    // 'pcmr',
    // 'codnation',
    // 'snd',
    // 'searchanddestroy',
    // 'clips',
    // 'coldwar',
    // 'gunfight',
    // 'Warzone',
    // 'CODBR',
    // 'MWBR',
    // 'CODWarzone',
    // 'ModernWarfare',
    // 'MW',
    // 'CODMW',
    // 'CoD',
    // 'clips',
    // 'blackops',
    // 'coldwar',
    // 'battleroyale',
    // 'modernwarfare',
    // 'modernwarfare2',
    // 'modernwarfare3',
    // 'modernwarfare4',
    // 'modernwarfareclips',
    // 'warzoneclips',
    // 'treyarch',
    // 'callofdutymodernwarfare',
    // 'Codtopplays',
    // 'blackops',
    // 'blackops2',
    // 'blackops3',
    // 'blackops4',
    // 'gaming',
    // 'blackout',
    // 'bo2',
    // 'gulag',
    // 'bo4',
    // 'battleroyale',
    // 'treyarchgaming',
    // 'callofdutyblackopscoldwar',
    // 'playstation',
    // 'blackopscoldwar',
    // 'warzonecod',
    // 'cod2020',
];
module.exports = [...new Set(hashtags)];
